### PR TITLE
teams command

### PR DESCRIPTION
**Pull request by woahtayo**
shows teams and players in it, very rough wasnt able to test, made mostly for my learning purposes

### CODE REVIEW

**Comment by MikeyUsersREC** [comment]
I think there's an indentation issue in the code.

**Comment by woahtayo** [comment]
apologise if there is, like i said wasn't able to do any testing so i never got any errors - i'll look into it

**Comment by MikeyUsersREC** [comment]
aight cool, just recommit when its fixed

**Comment by woahtayo** [comment]
think i might have missed some, checking again whooppppspssss

**Comment by MikeyUsersREC** [comment]
hope and pray fr

**Comment by bxrnt1** [comment]
❌ 🤓

**Pull request merged**
