### PR TITLE
Modpanel Command because why not

### PR DESCRIPTION
**Pull request by bugsbirb**
I am the best ERM developer. I am better than all of them. None of these developers could fathom how complicated this command is. It's unbelievably technical and uses the most advanced techniques and sesquipedalian uses of Python.

### CODE REVIEW

**Comment by MikeyUsersREC** [comment]
this is a pr not a dick sucking contest
please remove the profanity and swagness from function deco
ty in advance

**Comment by micheal-r** [comment]
real

**Comment by 247tide** [comment]
Erm what the sigma?

**Comment by 247tide** [comment]
Imagine if instead of calling this ERM we called it MRE because then instead of being ERM is would be backwards and not be called ERM but instead MRE which would be different than ERM
noFilter-1
.

**Comment by 247tide** [comment]
my image didn't wurk 😭

**Comment by NoahCxrest** [comment]
Do not troll in the repository. This is your first and final warning. You will be banned from contributing if you fail to do so.

**Review by NoahCxrest — APPROVED** [review]
self-approved - need to change func name for dashboard cmd later.

**Pull request merged**
