### PR TITLE
skip kick/bans w/ reasons

### PR DESCRIPTION
**Pull request by stefpower1**
QoL function

### CODE REVIEW

**Comment by stefpower1** [comment]
i hope i did this correctly lmao

**Comment by egelhaus** [comment]
What do you mean with that?

**Comment by stefpower1** [comment]
if the webhook from the :ban or :kick does not have a reason, it skips it. instead of having it make another ban/kick or modifying the existing one

**Comment by stefpower1** [comment]
having to make*

**Comment by shashankpandey04** [comment]
This approach will lead to Missing Argument Error as no reason parameter will be passed in the command.

**Comment by stefpower1** [comment]
isnt that what continue does? im more into js

**Comment by stefpower1** [comment]
fixed

**Comment by stefpower1** [comment]
its just return like in js lmao

**Comment by MikeyUsersREC** [comment]
lgtm

**Pull request merged**
