### PR TITLE
Smth for Noah

### PR DESCRIPTION
**Pull request by bugsbirb**
dk if it'll work didn't test it

### CODE REVIEW

**Comment by bugsbirb** [comment]
BRO OMG I LITERALLY SIGNED THE COMMIT

**Comment by NickIsADev** [comment]
🧢

**Comment by syinkboy** [comment]
I don't belive you.

**Comment by 247tide** [comment]
how about we ban erm from erm support server

**Comment by NoahCxrest** [comment]
This repository is not for non development related inquiries

**Comment by bxrnt1** [comment]
> how about we ban erm from erm support server

blah blah blah

**Comment by NoahCxrest** [comment]
> This repository is not for non development related inquiries

😇

**Comment by jaivardhandhanania1211** [comment]
This is a very good repository as I haven't even checked it. I'm only saying this as it's made by a sigma person.

**Pull request merged**
