### PR TITLE
New Features

### PR DESCRIPTION
**Pull request by shashankpandey04**
- Custom Command Edit
  - Now users can edit existing command by using `/custom manage` command.

- Shift Reports
  - On end of every shift Bot will send users report of their own shift with Total Moderations they issued while on-duty including custom punishments. Only if they have Shift Report enabled in Consent.

- Punishment Alert
  - If user is linked with ERM with help of `/link` command and have Punishment Alert enabled in Consent then bot will message them about their moderation when they get moderated in servers which use ERM for moderation.

### CODE REVIEW

**Comment by shashankpandey04** [comment]
Fixes:
- Custom Command List
  - Bot will send max 10 custom commands in one embed. If it exceeds 10 commands, then new embed will be send along with present one including other commands.
  
- ERLC Kills Command
  - Added `try/except` block in `/erlc kills` command, such that if guild icon is not present then also it proceeds with the command and doesn't throw any error on usage.

**Comment by NickIsADev** [comment]
nice! 👍 you're carrying the ERM team 🙏

**Comment by shashankpandey04** [comment]
New Features: Part 2

- **Discord Check Feature**
  - ERM will check available for ERLC players in discord server with help of Regex Matching such that display name with any format can be checked by bot. And return embed of Roblox username who are not in discord server.
  
  - Shift Termination Alert in DM due to Shift Wipe.
    - Bot will send DM to on-duty staff if there is any shift wipe in server.

**Comment by DezBirdss** [comment]
🤩

**Comment by shashankpandey04** [comment]
Update: Part 3

- Allowing `/duty admin` to forcefully open admin menu of users who don't have access to specific shit type. Passing an optional parameter true in the command ending will forcefully open that user admin panel. 
  - Suggestion Forum: https://discord.com/channels/987798554972143728/1239671186234020033

**Comment by NoahCxrest** [comment]
now you should make vehicle restrictions 🫡
this is being reviewed, thanks

**Comment by shashankpandey04** [comment]
Update: Part 4

- Vehicle Restrictions
  - Users can add roles who can use Exotic cars in-game, if players are found using exotic car in-game then it will send them a personal message 3 times. On the 4th violation it will send the alert in the channel setup by the server.
  - You can access Exotic Configuration from `/config` last page.
  
  *Note: This module is not tested with PRC API Yet & Exotic car names will be added soon in code as PRC API doesn't give car category in response.*

**Comment by NoahCxrest** [comment]
Thank you for this Part 4 PR—
Unfortunately; this is not how we want this feature to work.
Essentially, the preferred way of this working is basically having a spot in config in the ERLC module spot that says “Add Vehicle Restriction”—
There are two dropdowns, a role dropdown and a vehicle dropdown. The vehicle dropdown is multi select and has all the vehicles in the game.
So if I select on the role multiselect “Booster & VIP” and on the vehicle multi select I add all of the exotic cars, only the boosters and VIPs will be able to use that vehicle and no one else can.

**Comment by shashankpandey04** [comment]
Ohh All Right. In that case it just needs few modifications. Already working on that to shift it into ERLC Integration page. Just not pushed yet, will push as soon it's error free.

**Comment by notsliver** [comment]
hira, y'all can find all vehicles at [Link](https://emergency-response-liberty-county.fandom.com/wiki/Vehicles)

**Comment by NoahCxrest** [comment]
## Civilian Vehicles
Chevlon Antelope 1994
Stuttgart Executive 2021
Lawn Mower
Falcon Prime Eques 2003
Chevlon Camion 2002
Overland Apache 1995
Chevlon Captain 2006
Falcon Traveller 2003
Vellfire Evertt 1995
Vellfire Prima 2009
Elysion Slick 2014
Chevlon Landslide 2007
Navara Imperium 2020
Chevlon Commuter Van 2006
Leland LTS 2010
Chevlon Camion 2008
Chevlon Corbeta C2 1967
Bullhorn BH15 2009
Sentinel Platinum 1968
Chevlon LM 1984
Falcon Fission 2015
Chevlon Camion 2018
Falcon Advance 2018
Vellfire Runabout 1984
Falcon Scavenger 2016
Chevlon Revver 2005
Overland Apache 2011
Overland Buckaroo 2018
Chryslus Champion 2005
Vellfire Riptide 2020
Bullhorn Prancer 2011
Navara Boundary 2022
Celestial Type-6 2023
Arrow Phoenix Nationals 1977
Bullhorn Prancer 2015
Bullhorn Prancer Classic 1969
Bullhorn Determinator 2008
Chevlon Camion 2021
Falcon Stallion 350 1969
Falcon eStallion 2024
Chevlon Amigo Sport 2016
Chevlon Amigo ZL1 2011
Chevlon Platoro 2019
Vellfire Prairie 2022
Falcon Advance Bolt 2024
Falcon Rampage 2021
Averon Anodic 2024
Bullhorn Pueblo 2018
Falcon Traveller 2022
Falcon Advance Beast 2017
Overland Apache SFP 2020
Bullhorn Determinator SFP Fury 2022
Falcon Advance 2022
Bullhorn Prancer Widebody 2020
Leland Vault 2020
Bullhorn Determinator SFP Blackjack Widebody 2022
Averon S5 2010
Falcon Stallion 350 2015
Ferdinand Jalapeno Turbo 2022
BKM Munich 2020
Terrain Traveller 2022
Stuttgart Vierturig 2021
BKM Risen Roadster 2020
Averon RS3 2020
Celestial Truckatron 2024
Averon Q8 2022
Navara Horizon 2013
Vellfire Pioneer 2019
Stuttgart Landschaft 2022
Leland LTS5-V Blackwing 2023
Chevlon Corbeta TZ 2014
Chevlon Corbeta 8 2023
Takeo Experience 2021
Falcon Heritage 2021
Averon R8 2017
Surrey 650S 2016
Strugatti Ettore 2020

## Fire Department Vehicles
Fire Engine
Water Tender
Brush Falcon Advance+
Ladder Truck
Heavy Rescue
Squad Falcon Advance+
Special Operations Unit
Bullhorn Ambulance
International Ambulance
Paramedic SUV
Medical Bus
Utility Falcon Advance+
Falcon Advance
FD Bullhorn Prancer
FD Chevlon Camion
Mobile Command Center

## DOT Vehicles
1995 Vellfire Evertt
Flatbed Tow Truck
Cone Truck
2020 Falcon Advance+ Tow Truck
2020 Falcon Advance+ Roadside Assist
2019 Falcon Advance+ Utility
Street Sweeper
Salt Truck
Bucket Truck

**Comment by shashankpandey04** [comment]
Update: Part 5

- Whitelisted Vehicle
  - `Exotic Configuration` renamed to `Whitelisted Vehicle` and added in within ERLC Integration Menu in `/config` command.
  - Users need to Enter Vehicle name themselves in a Text Input Field, Existing data will load in the Modal when you try to edit it so no need to re-write whole data.
  
- Discord Check Updated
  - Discord Check will now check for both `username` and `Server Display Name`.

**Comment by shashankpandey04** [comment]
_Images Added_

image
image
image

**Comment by MikeyUsersREC** [comment]
- change "WhiteListed" to "Whitelisted"
- what shows if you put an incorrect name?
other than that lgtm

**Comment by shashankpandey04** [comment]
- Typo Fixed
- Added Fuzzy matching.
  -  Now allow minor differences in the vehicle names while ensuring the year part matches exactly. This helps in cases where there are typos in the vehicle names but avoids confusion with vehicles from different years.
  - e.g. Correct Name: Navara Imperium 2020, Entered Name: Navar Imprium 2020.

**Comment by shashankpandey04** [comment]
- Added `Python Levenshtein` for faster Typo matching.

**Comment by shashankpandey04** [comment]
Fixed merge conflicts in erm.py

**Comment by shashankpandey04** [comment]
**Bug Fix**
- Anti-Ping Module.

**Comment by shashankpandey04** [comment]
Another Bug Fix:
- Max On-Duty Staff Limit added. _Image added_
image

**Comment by shashankpandey04** [comment]
- *Modified ERLC Vehicle*
 - Command will send 20 vehicles in one embed to avoid reaching maximum word limit of discord.
 
- *Fixed missing Import*
 - `on_command_error.py` had missing imports.
  
- *New Custom Command Run Method*
 - Now users with management role can run custom commands without typing `custom run` as prefix, simply type custom command with prefix and mention channel where to post.
 - Example if custom command name is: `test`
  - `>test` and mention channel in front of it by giving a space.

**Comment by shashankpandey04** [comment]
- Admin Roles
 - An admin role is the role that can manage LOAs, RAs & other peoples' shifts but it cannot use server manage and config.
 
- ERM Command & Config Log
 - All administrative commands and configuration changes made by Admin & Management Roles. All commands such as Duty Admin, LOA Admin, RA Admin, Server Manage, Config, etc., as well as nearly all configuration changes, will be logged in this channel.
 
- OAuth2 check in Discord Check & Whitelisted Vehicle Check.

- _Bug Fix_
- Duty Manage Command > Break Start Timestamp bug.
- ERM Remote Commands: Ban permission check.
- Anti Ping

**Pull request merged**
