### PR TITLE
Put some swaz on it gromit

### PR DESCRIPTION
**Pull request by DezBirdss**
Make it actually change the status :+1:
(This should work)

### CODE REVIEW

**Comment by DezBirdss** [comment]
image_2024-05-30_152724996

**Comment by NoahCxrest** [comment]
Pls do not say unrelated things in this pr 😇😇

**Comment by DezBirdss** [comment]
I hope your heroin addiction makes you get hit by a bus

**Comment by DezBirdss** [comment]
activity=discord.Activity(type=discord.ActivityType.custom, name=status) DOES NOT WORK 😠

**Review by NoahCxrest — APPROVED** [review]
Good

**Comment by NoahCxrest** [comment]
didnt merge cuz u forgot to sign ur commits -- manually changed
thanks

**Pull request closed without merging**
